### ISSUE TITLE
App Crashes on Load

### ISSUE THREAD

**Issue by leathakkor** [cairoshell/cairoshell#215]
**Describe the bug**

When I start the application after it has crashed I seem to get an issue with the following stack trace in my event log:

Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at MS.Win32.UnsafeNativeMethods.RegisterClassEx(WNDCLASSEX_D)
   at MS.Win32.HwndWrapper..ctor(Int32, Int32, Int32, Int32, Int32, Int32, Int32, System.String, IntPtr, MS.Win32.HwndWrapperHook[])
   at System.Windows.Interop.HwndTarget+NotificationWindowHelper..ctor()
   at System.Windows.Interop.HwndTarget.EnsureNotificationWindow()
   at System.Windows.Interop.HwndTarget.AttachToHwnd(IntPtr)
   at System.Windows.Interop.HwndTarget..ctor(IntPtr)
   at System.Windows.Interop.HwndSource.Initialize(System.Windows.Interop.HwndSourceParameters)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.ShowHelper(System.Object)
   at CairoDesktop.Startup.Main(System.String[])

Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at MS.Win32.UnsafeNativeMethods.RegisterClassEx(WNDCLASSEX_D)
   at MS.Win32.HwndWrapper..ctor(Int32, Int32, Int32, Int32, Int32, Int32, Int32, System.String, IntPtr, MS.Win32.HwndWrapperHook[])
   at System.Windows.Application.EnsureHwndSource()
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at CairoDesktop.Startup.Main(System.String[])

**Expected behavior**

**System information:**
 - Windows version: Windows 10
 - Cairo version: Latest Pre-Release
 - 32-bit or 64-bit: 64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: yes

**Additional context**
I believe my computer was running low on Ram.

**Screenshots**

**Comment by leathakkor** [comment]
![screenshot 2018-11-02 19 36 38](https://user-images.githubusercontent.com/6441766/47947276-eae45400-ded6-11e8-9004-8075961aae0e.png)

My machine had over 4 GB of ram left. So i don't think I was actually out of ram

**Comment by dremin** [comment]
How many handles does Task Manager say are in use?

**Comment by leathakkor** [comment]
157000

**Comment by dremin** [comment]
That's pretty high.. if you open the Details tab and add the Handles column, does it look like there is an app leaking handles by chance?

**Comment by dremin** [comment]
Closing due to no response. The issue here appears to be that WPF choked due to a handle leak on the system.
