### ISSUE TITLE
ShellContextMenu Unhandled Exception

### ISSUE THREAD

**Issue by josuave** [cairoshell/cairoshell#242]
**Describe the bug**
Unhandled exception produced when right clicking icons on the DynamicDesktop

**Steps to reproduce**
1. rightclick the various desktop icons until exception is encountered

**Expected behavior**
ShellContextMenu should be shown

**System information:**
 - Windows version:  Windows 10 Pro (1803 build 17134.590)
 - Cairo version: 0.3.7010.34463 - Pre-Release
 - 32-bit or 64-bit:  64bit
 - In Cairo Settings > Advanced, is Cairo set as shell?:  Yes

**Additional context**
Please submit a bug report with a screenshot of this error. Thanks!
Message: Object reference not set to an instance of an object.
Target Site: IntPtr pathToRelPidl(System.String)
Version: 0.3.7010.34463

   at CairoDesktop.SupportingClasses.ShellContextMenu.pathToRelPidl(String path) in C:\.........\Cairo Desktop\SupportingClasses\ShellContextMenu.cs:line 117
   at CairoDesktop.SupportingClasses.ShellContextMenu.pathsToPidls(String[] files) in C:\.........\Cairo Desktop\SupportingClasses\ShellContextMenu.cs:line 103
   at CairoDesktop.SupportingClasses.ShellContextMenu..ctor(String[] files, Button sender, ItemSelectAction itemSelected) in C:\.........\Cairo Desktop\SupportingClasses\ShellContextMenu.cs:line 52
   at CairoDesktop.Desktop.CairoDesktopWindow_MouseRightButtonUp(Object sender, MouseButtonEventArgs e) in C:\.........\Cairo Desktop\Desktop.xaml.cs:line 465
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by dremin** [comment]
I'm fixing up a few memory and error handling issues locally and this should be fixed in my next commit :)

**Comment by dremin** [comment]
The shell context menu should work a lot more consistently now, let me know how it goes.

**Comment by dremin** [comment]
Included in the latest release.
