### ISSUE TITLE
Black screen after login 

### ISSUE THREAD

**Issue by brucbr** [cairoshell/cairoshell#364]
**Describe the bug**
Cairo starts after login, however then seems to crash without any error pop-up. Left with black screen, Task Manager shows no Cairo process running. (Cairo set as default shell)

**Steps to reproduce**
1. set Cairo as default shell
2. restart windows
3. login

**Expected behavior**
Cairo to start and be functional

**System information:**
 - Update 1909 (Windows 10)
 - M3.6971 (Tried earlier releases, same issue arises)
 - 64-bit
 - Set as Shell

**Additional context**
N/A

**Screenshots**
N/A

**Comment by dremin** [comment]
Could you please post the log file in `%localappdata%\Cairo_Development_Team\Logs`? Thanks!

**Comment by brucbr** [comment]
`[30/03/2020 10:55:18 AM] Info: #############################################

[30/03/2020 10:55:18 AM] Info: CairoDesktop

[30/03/2020 10:55:18 AM] Info: Version: 0.3.6947.0

[30/03/2020 10:55:19 AM] Info: Operating System: Microsoft Windows 10 Pro

[30/03/2020 10:55:19 AM] Info: OS Build: 10.0.18363.0

[30/03/2020 10:55:19 AM] Info: Processor Type: 64-bit

[30/03/2020 10:55:19 AM] Info: Startup Path: C:\Program Files\Cairo Shell

[30/03/2020 10:55:19 AM] Info: Running As: 64-bit Process

[30/03/2020 10:55:19 AM] Info: #############################################
`

**Comment by dremin** [comment]
Does Cairo launch if you start it while the Explorer shell is running?

**Comment by brucbr** [comment]
The reason it shows an earlier version is due to trying the earlier version in-case it was the latest version that had the issue.

It launches perfectly fine if explorer is also running.

**Comment by dremin** [comment]
> The reason it shows an earlier version is due to trying the earlier version in-case it was the latest version that had the issue.
Understood!

> It launches perfectly fine if explorer is also running.
Interesting. Could you adjust the logging level to Debug in Cairo Settings > Advanced, then try starting Cairo as shell again (after quitting Explorer) and post the resulting log?

**Comment by brucbr** [comment]
```[30/03/2020 11:21:18 AM] Info: #############################################

[30/03/2020 11:21:18 AM] Info: CairoDesktop

[30/03/2020 11:21:18 AM] Info: Version: 0.3.6947.0

[30/03/2020 11:21:18 AM] Info: Operating System: Microsoft Windows 10 Pro

[30/03/2020 11:21:18 AM] Info: OS Build: 10.0.18363.0

[30/03/2020 11:21:18 AM] Info: Processor Type: 64-bit

[30/03/2020 11:21:18 AM] Info: Startup Path: C:\Program Files\Cairo Shell

[30/03/2020 11:21:18 AM] Info: Running As: 64-bit Process

[30/03/2020 11:21:18 AM] Info: #############################################

[30/03/2020 11:21:18 AM] Debug: Loading Plugin Types. PluginProvider: 'FileSystemPluginProvider'.

[30/03/2020 11:21:18 AM] Debug: Sorting PluginDescriptor Collection. LeastDependentFirst: 'True'.

[30/03/2020 11:21:18 AM] Debug: Creating Plugins. # of Plugins: '0'.

[30/03/2020 11:21:18 AM] Debug: Sorting PluginDescriptor Collection. LeastDependentFirst: 'True'.

[30/03/2020 11:21:18 AM] Debug: Starting Plugins. # of Plugins: '0'.

[30/03/2020 11:21:19 AM] Debug: Created AppBar for handle 393878

[30/03/2020 11:21:19 AM] Debug: Window AppBar height is 23

[30/03/2020 11:21:19 AM] Debug: Starting WindowsTasksService

[30/03/2020 11:21:19 AM] Debug: Cloaked (2) window (Microsoft Text Input Application) hidden from taskbar

[30/03/2020 11:21:19 AM] Debug: Cloaked (2) window (Microsoft Store) hidden from taskbar

[30/03/2020 11:21:19 AM] Debug: Created AppBar for handle 197322

[30/03/2020 11:21:19 AM] Debug: TaskbarWindow AppBar height is 37

[30/03/2020 11:21:19 AM] Debug: Beginning screen setup

[30/03/2020 11:21:19 AM] Debug: Skipping screen setup due to no multi-mon features enabled

[30/03/2020 11:21:19 AM] Debug: Completed screen setup

[30/03/2020 11:21:19 AM] Debug: Added tray icon: Windows Security - Actions recommended. path: C:\Windows\System32\SecurityHealthSystray.exe GUID: ba82e2dc-f405-47ad-b032-cf0faa0e3933 UID: 100

[30/03/2020 11:21:19 AM] Debug: Added tray icon: Intel® HD Graphics path: C:\Windows\System32\igfxTray.exe GUID: 2d246b3b-ebd6-4d58-bd30-68861102aded UID: 0

[30/03/2020 11:21:19 AM] Debug: Modified tray icon: Windows Security - Actions recommended.

[30/03/2020 11:21:19 AM] Debug: Modified version to 4 on tray icon: Intel® HD Graphics

[30/03/2020 11:21:19 AM] Debug: Modified version to 4 on tray icon: Windows Security - Actions recommended.

[30/03/2020 11:21:19 AM] Debug: Activated: 0

[30/03/2020 11:21:19 AM] Debug: Redraw called: 2949940

[30/03/2020 11:21:19 AM] Debug: Redraw called: 2949940

[30/03/2020 11:21:19 AM] Debug: Redraw called: 262950

[30/03/2020 11:21:19 AM] Debug: Redraw called: 262950

[30/03/2020 11:21:19 AM] Debug: Activated: 0

[30/03/2020 11:21:19 AM] Debug: Redraw called: 328412

[30/03/2020 11:21:19 AM] Debug: Redraw called: 328412

[30/03/2020 11:21:19 AM] Debug: Activated: 0

[30/03/2020 11:21:19 AM] Debug: Redraw called: 262884

[30/03/2020 11:21:19 AM] Debug: Redraw called: 262884

```

**Comment by brucbr** [comment]
If you would prefer any logs to be put into pastebin, hastebin, etc instead, let me know.

**Comment by dremin** [comment]
Thanks! That appears to be the log from when Explorer was running. By chance is it not writing a log file when failing to start (you can check the modified date/time on the file)? Could you please check Event Viewer > Windows Logs > Application for entries for CairoDesktop and/or .NET?

**Comment by brucbr** [comment]
```Level	Date and Time	Source	Event ID	Task Category
Error	30/03/2020 11:21:19 AM	.NET Runtime	1026	None	Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.NewNormalizePath(System.String, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.DirectoryInfo.Init(System.String, Boolean)
   at CairoDesktop.Common.SystemDirectory..ctor(System.String, System.Windows.Threading.Dispatcher)
   at CairoDesktop.Startup.FetchStartupApps()
   at CairoDesktop.Startup.LoopStartupApps()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at CairoDesktop.Startup+<RunStartupApps>d__59.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Error	30/03/2020 11:04:01 AM	.NET Runtime	1026	None	Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.NewNormalizePath(System.String, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.DirectoryInfo.Init(System.String, Boolean)
   at CairoDesktop.Common.SystemDirectory..ctor(System.String, System.Windows.Threading.Dispatcher)
   at CairoDesktop.Startup.FetchStartupApps()
   at CairoDesktop.Startup.LoopStartupApps()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at CairoDesktop.Startup+<RunStartupApps>d__59.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Error	30/03/2020 10:55:16 AM	.NET Runtime	1025	None	Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: User restarted Cairo due to an exception.
Stack:
   at System.Environment.FailFast(System.String)
   at CairoDesktop.App.Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr, IntPtr, IntPtr, Int32)
   at MS.Win32.UnsafeNativeMethods.CoInternetCreateSecurityManager(System.Object, System.Object ByRef, Int32)
   at MS.Internal.SecurityHelper.MapUrlToZoneWrapper(System.Uri)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, System.Guid ByRef, Boolean ByRef, System.IO.Stream ByRef, System.IO.UnmanagedMemoryStream ByRef, Microsoft.Win32.SafeHandles.SafeFileHandle ByRef)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, Boolean)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at CairoDesktop.Desktop+<>c__DisplayClass40_0.<GetCairoBackgroundBrush_Image>b__0()
   at CairoDesktop.Desktop.TryAndEat(System.Action)
   at CairoDesktop.Desktop.GetCairoBackgroundBrush_Image(System.String, CairoWallpaperStyle)
   at CairoDesktop.Desktop.GetCairoBackgroundBrush_Windows()
   at CairoDesktop.Desktop.GetCairoBackgroundBrush()
   at CairoDesktop.Desktop.setBackground()
   at CairoDesktop.Desktop..ctor()
   at CairoDesktop.Startup.Main(System.String[])

Error	30/03/2020 10:46:58 AM	.NET Runtime	1026	None	Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.NewNormalizePath(System.String, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.DirectoryInfo.Init(System.String, Boolean)
   at CairoDesktop.Common.SystemDirectory..ctor(System.String, System.Windows.Threading.Dispatcher)
   at CairoDesktop.Startup.FetchStartupApps()
   at CairoDesktop.Startup.LoopStartupApps()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at CairoDesktop.Startup+<RunStartupApps>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Error	30/03/2020 10:45:29 AM	.NET Runtime	1026	None	Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.NewNormalizePath(System.String, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.DirectoryInfo.Init(System.String, Boolean)
   at CairoDesktop.Common.SystemDirectory..ctor(System.String, System.Windows.Threading.Dispatcher)
   at CairoDesktop.Startup.FetchStartupApps()
   at CairoDesktop.Startup.LoopStartupApps()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at CairoDesktop.Startup+<RunStartupApps>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Error	30/03/2020 10:41:53 AM	.NET Runtime	1026	None	Application: CairoDesktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.IO.Path.NewNormalizePath(System.String, Int32, Boolean)
   at System.IO.Path.NormalizePath(System.String, Boolean, Int32, Boolean)
   at System.IO.Path.GetFullPathInternal(System.String)
   at System.IO.DirectoryInfo.Init(System.String, Boolean)
   at CairoDesktop.Common.SystemDirectory..ctor(System.String, System.Windows.Threading.Dispatcher)
   at CairoDesktop.Startup.FetchStartupApps()
   at CairoDesktop.Startup.LoopStartupApps()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at CairoDesktop.Startup+<RunStartupApps>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


```

**Comment by brucbr** [comment]
It says the framework version is 4.0 even though the windows version is later than 1709.

I'll try downloading a newer version and see how it goes.

**Comment by brucbr** [comment]
Nevermind, apparently a newer version is already installed...

**Comment by dremin** [comment]
Thanks, the event log helps a lot! I think I see the problem, and will post a build for you to try shortly.

**Comment by brucbr** [comment]
Thank you.

**Comment by dremin** [comment]
Could you please try [this build](https://ci.appveyor.com/api/buildjobs/qdq4ij4fkjugy24m/artifacts/Installer%2FCairoSetup_64bit.exe)? Thanks!

**Comment by brucbr** [comment]
It works! Thanks!

If you don't mind me asking (and if it's not to hard), what was the issue?

**Comment by dremin** [comment]
Great, glad it is working!

The .NET framework was failing in [this function](https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,dc6448549d442c9e,references) when Cairo was loading the startup apps folders. I'm guessing that the system is either giving Cairo the wrong path for the folder, or a path that includes invalid characters.

**Comment by brucbr** [comment]
Thanks. I'll close the issue now.
