### ISSUE TITLE
Error/Crash when user right-clicks on browse for folder popup

### ISSUE THREAD

**Issue by HoldenRiot** [cairoshell/cairoshell#483]
**Describe the bug**
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?
Please submit a bug report with a screenshot of this error. Thanks! 
Message: External component has thrown an exception.
Target Site: IntPtr SHBrowseForFolder(BROWSEINFO)
Version: 0.3.7147.0
   at System.Windows.Forms.UnsafeNativeMethods.Shell32.SHBrowseForFolder(BROWSEINFO lpbi)
   at System.Windows.Forms.FolderBrowserDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at CairoDesktop.DesktopNavigationToolbar.btnBrowse_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.R...

**Steps to reproduce**
1. With Cairo open, Click the Choose Folder icon on the Desktop to browse a folder.
3. With the Browse folder popup open, right-click anywhere on the modal popup such as on a folder name and Error/Crash is occurs. 

**Expected behavior**
Cairo does not crash or throw error when user right-clicks the Browse for folder popup.

**System information:**
 - Windows version:  10
 - Cairo version: 
 - 32-bit or 64-bit: 
 - In Cairo Settings > Advanced, is Cairo set as shell?: 

**Additonal Information**
 - Is able to be replcated running as Administrator and without.

**Screenshots**
[https://imgur.com/3g4wO9q](https://imgur.com/3g4wO9q)

**Comment by dremin** [comment]
It looks like this is an issue occurring in MS code, but we can probably handle it more gracefully.

**Comment by dremin** [comment]
This should be fixed in the latest release. Could you please check if this is fixed for you?
