### ISSUE TITLE
Cairo 0.4.112.21595 doesn't start (after upgrade)

### ISSUE THREAD

**Issue by boekabart** [cairoshell/cairoshell#618]
**Describe the bug**
After upgrading, Cairo no longer starts.
This popup appears. Always.
```
---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?



Please submit a bug report with a screenshot of this error. Thanks! 

Message: Method not found: 'Void CairoDesktop.Application.Interfaces.ICairoApplication.AddResource(System.Object)'.

Target Site: Void SetTheme(System.String)

Version: 0.4.112.21595



   at CairoDesktop.Services.ThemeService.SetTheme(String theme)

   at CairoDesktop.Services.ThemeService.SetThemeFromSettings()

   at CairoDesktop.CairoApplication.OnStartup(StartupEventArgs e)

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
Yes   No   
---------------------------
```

If I press Yes, the same dialog appears. If no, nothing happens. No 'desktop'.

**Expected behavior**
Cairo Starts

**System information:**
 - Windows version: Server 2019
 - Cairo version: 0.4.112.21595
 - 32-bit or 64-bit: 64-bit
 - In Cairo Settings > Advanced, is Cairo set as shell?: Yes (can't check, but Cairo IS the shell)

**Comment by dremin** [comment]
This error looks like mismatched files got installed. Could you please try reinstalling the latest version (0.4.133)?
