### ISSUE TITLE
Cairo crash while in Cairo Settings dialog

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#63]
```
---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?



Please submit a bug report with a screenshot of this error. Thanks! 

Message: The parameter is incorrect

Target Site: Int32 GetWindowText(System.Runtime.InteropServices.HandleRef, System.Text.StringBuilder, Int32)

Version: 0.3.6545.26403



   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)

   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()

   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()

   at System.Windows.ContextLayoutManager.fireAutomationEvents()

   at System.Windows.ContextLayoutManager.UpdateLayout()

   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)

   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()

   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)

   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)

   ...
---------------------------
Yes   No   
---------------------------
```

**Comment by coldacid** [comment]
```
---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?



Please submit a bug report with a screenshot of this error. Thanks! 

Message: The parameter is incorrect

Target Site: Int32 GetWindowText(System.Runtime.InteropServices.HandleRef, System.Text.StringBuilder, Int32)

Version: 0.3.6545.26403



   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)

   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()

   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()

   at System.Windows.ContextLayoutManager.fireAutomationEvents()

   at System.Windows.ContextLayoutManager.UpdateLayout()

   at System.Windows.Controls.VirtualizingStackPanel.<>c__DisplayClass94_0.<InitializeViewport>b__0()

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Deleg...
---------------------------
Yes   No   
---------------------------
```

**Comment by dremin** [comment]
Thanks! I'll have this fixed in the next build. Were there any specific steps that you took to produce this error?

**Comment by coldacid** [comment]
Nothing specific that I can recall, no.

**Comment by dremin** [comment]
This should be resolved with the latest build. Please update this if it is not fixed.
