### ISSUE TITLE
Random crashes after most recent updates

### ISSUE THREAD

**Issue by yuukidesu9** [cairoshell/cairoshell#655]
**Describe the Bug**
Cairo Shell randomly freezes, crashes and/or restarts when an app opened in the dock is hovered and at random times.

**Steps to Reproduce**
- Open application
- Hover mouse button over it

**Expected Behavior**
Cairo working normally and allowing to select the window in question.

**System Information**
Cairo Shell 0.4.174.64607 Pre-Release on Windows 8.1 (not replacing Explorer)

**Additional Context**
![image](https://user-images.githubusercontent.com/19637709/148624698-f7b580d2-e3c7-443d-a7c9-51978004daf6.png)

**Comment by yuukidesu9** [comment]
Here's the latest log contents with the same exact error, just for the sake of completion:

```
[1/24/2022 9:14:53 AM] Info: [Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.

[1/24/2022 9:14:53 AM] Info: [Microsoft.Hosting.Lifetime] Hosting environment: Production

[1/24/2022 9:14:53 AM] Info: [Microsoft.Hosting.Lifetime] Content root path: C:\Program Files\Cairo Shell\

[1/24/2022 9:14:53 AM] Info: [CairoDesktop.CairoApplicationInitializationService] Version: 0.4.174.64607

[1/24/2022 9:14:53 AM] Info: [CairoDesktop.CairoApplicationInitializationService] Operating System: Windows 8.1 Pro 6.3.9600.0

[1/24/2022 9:14:53 AM] Info: [CairoDesktop.CairoApplicationInitializationService] Processor Type: 64-bit

[1/24/2022 9:14:53 AM] Info: [CairoDesktop.CairoApplicationInitializationService] Running As: 64-bit Process

[1/24/2022 9:14:53 AM] Info: [CairoDesktop.CairoApplicationInitializationService] Configured as shell: False

[1/24/2022 9:14:53 AM] Info: [CairoDesktop.CairoApplicationInitializationService] Running as shell: False

[1/24/2022 9:16:33 AM] Error: TasksService: Error in ShellWinProc. 
	:::Exception Details:::
	System.InvalidOperationException: '[Unknown]' property does not point to a DependencyObject in path '(0).(1)[0].(2)'.
	   at System.Windows.Media.Animation.Storyboard.VerifyPathIsAnimatable(PropertyPath path)
	   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
	   at System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
	   at System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
	   at System.Windows.Media.Animation.BeginStoryboard.Begin(DependencyObject targetObject, INameScope nameScope, Int64 layer)
	   at System.Windows.StyleHelper.InvokeActions(TriggerBase triggerBase, DependencyObject triggerContainer, TriggerActionCollection actions, Style style, FrameworkTemplate frameworkTemplate)
	   at System.Windows.StyleHelper.InvokeEnterOrExitActions(TriggerBase triggerBase, Boolean oldState, Boolean newState, DependencyObject triggerContainer, Style style, FrameworkTemplate frameworkTemplate)
	   at System.Windows.StyleHelper.InvokeDataTriggerActions(TriggerBase triggerBase, DependencyObject triggerContainer, BindingBase binding, BindingValueChangedEventArgs bindingChangedArgs, Style style, FrameworkTemplate frameworkTemplate, UncommonField`1 dataField)
	   at System.Windows.StyleHelper.InvokeApplicableDataTriggerActions(Style style, FrameworkTemplate frameworkTemplate, DependencyObject container, BindingBase binding, BindingValueChangedEventArgs e, UncommonField`1 dataField)
	   at System.Windows.StyleHelper.OnBindingValueInTemplateChanged(Object sender, BindingValueChangedEventArgs e)
	   at System.Windows.Data.BindingExpressionBase.ChangeValue(Object newValue, Boolean notify)
	   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
	   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
	   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
	   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
	   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
	   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
	   at ManagedShell.WindowsTasks.ApplicationWindow.OnPropertyChanged(String PropertyName)
	   at ManagedShell.WindowsTasks.TasksService.ShellWinProc(Message msg)
```

**Comment by dremin** [comment]
I think I found the cause of this. Are you using the 'Flat' theme by chance?

**Comment by yuukidesu9** [comment]
Yep, I'm using Flat theme.

**Comment by dremin** [comment]
Thanks for confirming! If you'd like to test, [this build](https://github.com/cairoshell/cairoshell/suites/5272004506/artifacts/162977349) (GitHub login required to download) should have the fix.

**Comment by yuukidesu9** [comment]
So far, so good. Works as intended. Thanks.
If I have any issues, I'll update the thread.
