### ISSUE TITLE
Crash when opening folder from opened folder on menu bar

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#91]
I recieved this message after selecting a folder from an opened folder on the Cairo menu bar.

```
---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?

Please submit a bug report with a screenshot of this error. Thanks! 
Message: Object reference not set to an instance of an object.
Target Site: Void btnFile_Click(System.Object, System.Windows.RoutedEventArgs)
Version: 0.3.6617.35229

   at CairoDesktop.Cairo.btnFile_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersI...
---------------------------
Yes   No   
---------------------------
```

**Comment by dremin** [comment]
Thanks for the report! I'll add some additional checks to avoid crashing here. Was there anything notable about this folder? Had it been deleted?

**Comment by coldacid** [comment]
Nope, nothing notable about it at all.

**Comment by dremin** [comment]
Do you have 'Enable Desktop' unchecked in Cairo Settings?

**Comment by coldacid** [comment]
Yeah, I keep that off. I prefer the original desktop.

**Comment by dremin** [comment]
Thanks for confirming, I found the issue and it will be fixed in the next build.

**Comment by dremin** [comment]
This is now fixed in the latest build, please update this if you continue to have the issue.
