### ISSUE TITLE
Crash on wake-up

### ISSUE THREAD

**Issue by coldacid** [cairoshell/cairoshell#94]
Got this after waking up my laptop and logging in, without any interaction with Cairo from system wake-up.

```
---------------------------
Cairo Desktop Error
---------------------------
Would you like to restart Cairo?

Please submit a bug report with a screenshot of this error. Thanks! 
Message: The parameter is incorrect
Target Site: Int32 GetWindowText(System.Runtime.InteropServices.HandleRef, System.Text.StringBuilder, Int32)
Version: 0.3.6623.33517

   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   ...
---------------------------
Yes   No   
---------------------------
```

**Comment by dremin** [comment]
Thanks! I wasn't able to reproduce with those steps but I took a look and made a change for the next build that should hopefully avoid this in the future.

**Comment by dremin** [comment]
This has been addressed in the latest release.
